version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ec2-user/app/travis/spb_build/

hooks:
  AfterInstall: # 배포 끝나면 아래 명령어를 실행
    - location: execute-spb_deploy.sh
      timeout: 180
