# main
spring:
  profiles:
    active: local # 기본 환경 선택
    
    
    
# common setting
--- 
spring.profiles: common

server:
  port: 8085
  error.whitelabel.enabled: false

spring:   
  main:
    allow-bean-definition-overriding: true

  output:
    ansi:
      enabled: always
      
  devtools:
    livereload:
      enabled: true
    add-properties: false
  freemarker:
    cache: false
    
  jpa:
    open-in-view: false
    
  servlet:
    multipart:
      enabled: true
      max-file-size: 3MB
      max-request-size: 3MB
      file-size-threshold: 1MB

# local 환경
---
spring:
  profiles: local
  profiles.include: common

  datasource:
    hikari:
      jdbc-url: jdbc:mariadb://localhost:3306/contact?useSSL=false
      username: root
      password: test123 
      driver-class-name: org.mariadb.jdbc.Driver
#    initialization-mode: always
#    data: classpath:init.sql
        
  jpa:
    database: mysql
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
  
logging:
  level:
    org.springframework.web.client: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
  file: ./log/local

server:
  ssl:
    enabled: true
    key-store: keystore.p12
    key-store-password: test123
    key-store-type: PKCS12
    key-alias: bns-ssl
  port: 8443



# local에서 test
---
spring.profiles: test
spring.profiles.include: common

spring:
  h2:
    console:
      enabled: true
      path: /h2/
      settings:
        trace: true
        web-allow-others: true
        
  datasource:
    hikari:
#      jdbc-url: jdbc:h2:mem://localhost/~/contact;DB_CLOSE_ON_EXIT=false;DB_CLOSE_DELAY=-1;MVCC=TRUE
      jdbc-url: jdbc:h2:mem:contact;DB_CLOSE_ON_EXIT=false;DB_CLOSE_DELAY=-1;MVCC=TRUE
#      jdbc-url: jdbc:h2:tcp://localhost/~/contact;DB_CLOSE_ON_EXIT=false;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE;MVCC=TRUE
      username: sa
      password: 
      driver-class-name: org.h2.Driver
    data: classpath:init.sql
  
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

logging:
  level:
    org.springframework.web.client: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE

#server:
#  ssl:
#    enabled: true
#    key-store: keystore.p12
#    key-store-password: test123
#    key-store-type: PKCS12
#    key-alias: bns-ssl
#  port: 8443


# production 환경 
---
spring.profiles: prod
spring.profiles.include: real-db, common
  
logging:
  file: ./log/prod