# local
spring:
  profiles:
    active: local # 기본 환경 선택

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: false 
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  datasource:
        url: jdbc:mariadb://localhost:3306/contact
        username: root
        password: test123 
        driver-class-name: org.mariadb.jdbc.Driver
        
# local 환경
---
spring.profiles: local

server:
  port: 8085
logging:
  level:
    com.soda.phonebook: DEBUG
  file: ./log/local

# production 환경 
---
spring.profiles: prod
spring.profiles.include: real-db

server:
  port: 8085
  
logging:
  file: ./log/prod