# local
spring:
  profiles:
    active: local # 기본 환경 선택

  output:
    ansi:
      enabled: always
        
# local 환경
---
spring.profiles: local

server:
  port: 8080

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
  datasource:
        url: jdbc:mariadb://localhost:3306/contact
        username: root
        password: test123 
        driver-class-name: org.mariadb.jdbc.Driver
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    com.soda.phonebook: DEBUG
    org.springframework.web.client: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
  file: ./log/local
  
# production 환경 
---
spring.profiles: prod
spring.profiles.include: real-db

server:
  port: 8080
  
logging:
  file: ./log/prod