INSERT INTO USER(CREATED_DATE , MODIFIED_DATE , NAME ) VALUES ( CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), '테스트유저'); 

INSERT INTO CONTACT(CREATED_DATE , MODIFIED_DATE, MEMO, NAME, PHOTO, CONTACT_TYPE, USER_ID)  
VALUES (CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), '메모', '정소연', null, 0, 1);

INSERT INTO CATEGORY( CREATED_DATE, MODIFIED_DATE, NAME, DATA_TYPE, USER_ID, IS_DEFAULT) 
VALUES (CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), '집', 0, 1, 1);
INSERT INTO CATEGORY( CREATED_DATE, MODIFIED_DATE, NAME, DATA_TYPE, USER_ID, IS_DEFAULT) 
VALUES (CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), '회사', 0, 1, 1); 
INSERT INTO CATEGORY( CREATED_DATE, MODIFIED_DATE, NAME, DATA_TYPE, USER_ID, IS_DEFAULT) 
VALUES (CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), '기타', 0, 1, 1);
INSERT INTO CATEGORY( CREATED_DATE, MODIFIED_DATE, NAME, DATA_TYPE, USER_ID, IS_DEFAULT) 
VALUES (CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), '커스텀', 0, 1, 0); 
INSERT INTO CATEGORY( CREATED_DATE, MODIFIED_DATE, NAME, DATA_TYPE, USER_ID, IS_DEFAULT) 
VALUES (CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), '개인', 2, 1, 1);
INSERT INTO CATEGORY( CREATED_DATE, MODIFIED_DATE, NAME, DATA_TYPE, USER_ID, IS_DEFAULT) 
VALUES (CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), '회사', 2, 1, 1);
INSERT INTO CATEGORY( CREATED_DATE, MODIFIED_DATE, NAME, DATA_TYPE, USER_ID, IS_DEFAULT)
VALUES (CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), '기타', 2, 1, 1);
INSERT INTO CATEGORY( CREATED_DATE, MODIFIED_DATE, NAME, DATA_TYPE, USER_ID, IS_DEFAULT)
VALUES (CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), '커스텀', 2, 1, 0);

INSERT INTO DiGIT(CREATED_DATE , MODIFIED_DATE, FIRST , SECOND , THIRD , REP , CATEGORY_ID , CONTACT_ID ) 
VALUES (CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), '010','1234','5678', 1, 1, 1); 

INSERT INTO INFO(DTYPE ,CREATED_DATE , MODIFIED_DATE,CONTENTS, CATEGORY_ID ,CONTACT_ID )
VALUES ('D',CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'test@test.com', 4, 1);
INSERT INTO INFO(DTYPE ,CREATED_DATE , MODIFIED_DATE,CONTENTS, CATEGORY_ID ,CONTACT_ID )
VALUES ('E',CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'company@test.com', 4, 1);

INSERT INTO TAG ( CREATED_DATE , MODIFIED_DATE , NAME, USER_ID)
VALUES (CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), '친구', 1);

INSERT INTO TAG_CONTACT VALUES (1,1);
